// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/kabanboard/issue/Badge.vue')['default']
    ClosedIssues: typeof import('./src/components/kabanboard/ClosedIssues.vue')['default']
    HeaderGuest: typeof import('./src/components/header/HeaderGuest.vue')['default']
    HeaderUser: typeof import('./src/components/header/HeaderUser.vue')['default']
    IssueCard: typeof import('./src/components/kabanboard/issue/IssueCard.vue')['default']
    IssuesInProgress: typeof import('./src/components/kabanboard/IssuesInProgress.vue')['default']
    KabanBoard: typeof import('./src/components/kabanboard/KabanBoard.vue')['default']
    OpenIssues: typeof import('./src/components/kabanboard/OpenIssues.vue')['default']
    ReviewIssues: typeof import('./src/components/kabanboard/ReviewIssues.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Urgency: typeof import('./src/components/kabanboard/issue/Urgency.vue')['default']
  }
}

export { }
